repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^.+\.tpl\.yaml$
      - id: check-added-large-files

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports-repo
        args:
          - "-local"
          - "github.com/beeper/bridge-manager"
          - "-w"
      - id: go-vet-repo-mod
      - id: go-staticcheck-repo-mod
